<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="views/css/changePass.css">
    <script type="text/javascript" src="views/js/PasswordValidation.js"></script>
</head>
<?php 
if ($_SESSION['role']==="admin") {
    require_once("views/AdminHome.phtml");
}  
if ($_SESSION['role']==="staff") {
    require_once("views/StaffHome.phtml");
} 
if ($_SESSION['role']==="patient") {
    require_once("views/PatientHome.phtml");
}  
if ($_SESSION['role']==="doctor") {
    require_once("views/DoctorHome.phtml");
} 
if (isset($_GET["user_id"])) {
    $id = $_GET["user_id"]; 
}
?>
<h2><center>Change Password</center></h2>
<div class="container">
    <form method="POST" action="ChangePasswordPost?user_id=<?= $id?>" onsubmit ="return PasswordValidation(this)">
        <fieldset>
            <div class="form-group row">
                <label for="ChangePassword">Password</label>
                <div class="col-sm-4">
                    <input type="password" name="ChangePassword" id="ChangePassword" placeholder="Enter Password" >
                </div>
            </div>
            <div class="form-group row">
                <label for="ConfirmPassword">Confirm Password</label>
                <div class="col-sm-4">
                    <input type="password" name="ConfirmPassword" id="ConfirmPassword" placeholder="Confirm Password" >
                </div>
            </div>
            <div class="form-group row">
                <div class="offset-sm-2 col-sm-10">
                    <input type="submit" name="submit" value="Update">
                </div>
            </div>
            <div>
                <center><span id="error"></span></center>
                <center><span id="success"></span></center>
            </div>
        </fieldset>
    </form>
</div>