<head>
    <link rel="stylesheet" href="views/css/doctorReport.css">
</head>
<?php
if ($_SESSION['role']==="admin") {
  require_once("views/AdminHome.phtml");
  $doctors = new DoctorData();
  $doctorsList = $doctors->listDoctors(); 
  $country = new CountryData();
  $state = new StateData();
?>
<div>
    <button onclick= "DoctorReport()" class="report">Export</button>
</div>
<div>
    <table>
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Contact</th>
            <th>Email</th>
            <th>Qualification</th>
            <th>DOB</th>
            <th>District</th>
            <th>State</th>
            <th>Country</th>
            <th>Pincode</th>
        </thead>
        <tbody>
            <?php while ($row = $doctorsList->fetch(PDO::FETCH_ASSOC)) {
                ?>
                <tr>
                    <td><?= $row['d_id']?></td>
                    <td><?= $row['firstname'] ?></td>
                    <td><?= $row['lastname'] ?></td>
                    <td><?= $row['gender'] ?></td>
                    <td><?= $row['contact'] ?></td>
                    <td><?= $row['email'] ?></td>
                    <td><?= $row['qualification'] ?></td>
                    <td><?= date("d-M-Y",strtotime($row['dob']))  ?></td>
                    <td><?= $row['district'] ?></td>
                    <td><?php 
                    if(is_numeric($row['state'])){
                        $State = $state->SelectStateName($row['state']);
                        echo $State;
                    } else {
                        echo $row['state'];
                    }
                    ?></td>
                    <td><?php 
                    if(is_numeric($row['country'])){
                        $Country = $country->SelectCountryName($row['country']);
                        echo $Country;
                    } else {
                        echo $row['country'];
                    }
                    ?></td>
                    <td><?= $row['pincode'] ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<?php } ?>