<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="views/css/doctor.css">
</head>
<?php 
if ($_SESSION['role']==="admin") {
  require_once("views/AdminHome.phtml");
} 
?>
<?php 
if ($_SESSION['role']==="staff") {
  require_once("views/StaffHome.phtml");
} 
?>
<?php 
    if (isset($_GET['d_id'])) {
        $id = $_GET['d_id'];
        $update = true;
        $doctor = new DoctorData();
        $result = $doctor->ViewDoctor($id);
    } else {
        $id = 0;
        $update = false;
    }
?>
<div class="container">
    <form name="doctorLogin" role="form" method="POST" class="doctorLogin" action="DoctorPost" onsubmit="return doctorValidation('doctorLogin')" enctype="multipart/form-data" autocomplete="on">
        <fieldset>
            <?php if($update===true): ?>
                <center><legend>Update Doctor</legend></center>
            <?php else: ?>
                <center><legend>Add Doctor</legend></center>
            <?php endif ?>
            <p>
                <?php if($update===true): ?>
                    <input type="hidden" id="d_id" name="d_id" value="<?php echo $id; ?>">
                <?php endif ?>
            </p>
            <div class="form-group row">
                <label for="firstname">First Name</label>
                <div class="col-sm-4">
                    <input type="text" id="firstname" name="firstname" placeholder="Enter your first name"
                    <?php if($update === true): ?>
                        value="<?php echo $result['firstname']?>" 
                    <?php else: ?>
                        value="" 
                    <?php endif ?> required>
                </div>
            </div>
            <div class="form-group row">
                <label for="lastname">Last Name</label>
                <div class="col-sm-4">
                    <input type="text" id="lastname" name="lastname" placeholder="Enter your last name"
                    <?php if($update === true): ?>
                        value="<?php echo $result['lastname']?>" 
                    <?php else: ?>
                        value="" 
                    <?php endif ?> required> 
                </div>
            </div>
            <div class="form-group row">
                <label>Gender</label><br>
                <div class="col-sm-4">
                    <?php if($update === true): ?>
                        <input type="radio" id="male" name="gender" <?php if($result['gender']=='male') { ?> checked='checked' <?php } ?> value="male"></input>
                    <?php else: ?>
                        <input type="radio" id="male" name="gender" value="Male">
                    <?php endif ?>
                    <label for="male" id="gender">Male</label>
                    <?php if($update === true): ?>
                        <input type="radio" id="female" name="gender" <?php if($result['gender']=='female') { ?> checked='checked' <?php } ?> value="female"></input>
                    <?php else: ?>
                        <input type="radio" id="female" name="gender" value="female">
                    <?php endif ?>
                    <label for="female" id="gender">Female</label>
                </div>
            </div>
            <div class="form-group row">
                <label for="dob">Date Of Birth</label>
                <div class="col-sm-4">
                    <input type="date" id="dob" name="dob" placeholder="Enter your date of birth"
                    <?php if($update === true): ?>
                        value="<?php echo $result['dob']?>" 
                    <?php else: ?>
                        value="" 
                    <?php endif ?> required>
                </div>
            </div>
            <div class="form-group row">
                <label for="age">Age</label>
                <div class="col-sm-4">
                    <input type="number" id="age" name="age" placeholder="Enter your age" 
                    <?php if($update === true): ?>
                        value="<?php echo $result['age']?>" 
                    <?php else: ?>
                        value="" 
                    <?php endif ?> required>
                </div>
            </div>
            <div class="form-group row">
                <label for="email">Email Address</label>
                <div class="col-sm-4">
                    <input type="email" id="email" name="email" placeholder="Enter email address"
                    <?php if($update === true): ?>
                        value="<?php echo $result['email']?>" 
                    <?php else: ?>
                        value="" 
                    <?php endif ?> required>
                </div>
            </div>
            <div class="form-group row">
                <label for="contact">Contact Number</label>
                <div class="col-sm-4">
                    <input type="tel" id="contact" name="contact" pattern="[0-9]{10}" placeholder="Enter mobile number" 
                    <?php if($update === true): ?>
                        value="<?php echo $result['contact']?>" 
                    <?php else: ?>
                        value="" 
                    <?php endif ?> required>
                </div>
            </div>
            <?php if($update === false) { ?>
                <div class="form-group row">
                    <label for="password">Password</label>
                    <div class="col-sm-4">
                        <input type="password" id="password" name="password" placeholder="Enter Password" required>
                    </div>
                </div>
            <?php } ?>
            <div class="form-group row">
                <label for= "address">Address</label><br>
                <div class="col-sm-4">
                    <?php if($update === true): ?>
                        <textarea id="address" name="address" rows="4" cols="30"><?php echo $result['address']?></textarea>
                    <?php else: ?>
                        <textarea id="address" name="address" rows="4" cols="30" placeholder="Enter your address here"></textarea>
                    <?php endif ?>
                </div>
            </div>
            <div class="form-group row">
                <label for="country">Country</label>
                <div class="col-sm-4">
                    <select id="country" name="country" onchange="getStateByCountry(this.value, 'state');">
                    <option value="Select Country" >Select Country</option>
                    <?php 
                    $country = new CountryData();
                    $result1 = $country->selectCountry(); 
                    while ($row = $result1->fetch(PDO::FETCH_ASSOC)) {?>
                    <?php if($update === true): ?>
                        <option value=<?php echo $row['country_id']; ?> <?php if($result['country'] == $row['country_name']){ echo "selected";}?>> <?php echo $row['country_name'];?></option>
                    <?php else: ?>
                        <option value=<?php echo $row['country_id']; ?>><?php echo $row['country_name'];?></option>
                    <?php endif ?>
                        <?php } ?>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="state">State</label>
                <div class="col-sm-4">
                    <select id="state" name="state">
                        <?php
                        if($update === true): ?>
                            <option value=<?php echo $result['state']; ?> <?php if($result['state']){ echo "selected";}?>> <?php echo $result['state'];?></option>
                        <?php else: ?>
                            <option value="Select State" >Select State</option>
                        <?php endif ?>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="district">District</label>
                <div class="col-sm-4">
                    <input type="text" id="district" name="district" placeholder="Enter district"
                    <?php if($update === true): ?>
                        value = "<?php echo $result['district']?>"
                    <?php else: ?>
                        <?php echo ""?>
                    <?php endif ?> required>
                </div>
            </div>
            <div class="form-group row">
                <label for="pincode">Postal code</label>
                <div class="col-sm-4">
                    <input type="text" id="pincode" name="pincode" placeholder="Enter pincode"
                    <?php if($update === true): ?>
                        value = "<?php echo $result['pincode']?>"
                    <?php else: ?>
                        <?php echo ""; ?>
                    <?php endif ?> required>
                </div>
            </div>
            <div class="form-group row">
                <label for="qualification">Qualification</label>
                <div class="col-sm-4">
                    <input type="text" id="qualification" name="qualification" placeholder="Enter your qualification"
                    <?php if($update === true): ?>
                        value = "<?php echo $result['qualification']?>"
                    <?php else: ?>
                        <?php echo ""; ?>
                    <?php endif ?> required>
                </div>
            </div>
            <div class="form-group row">
                <label for="specialist">Specialist</label>
                <div class="col-sm-4">
                    <select id="specialist" name="specialist">
                        <?php if($update === true): ?>
                            <option value=<?php echo $result['specialist']; ?> <?php if($result['specialist'] == $result['specialist']){ echo "selected";}?>> <?php echo $result['specialist'];?></option>
                            <option value="General">General</option>
                            <option value="Nutritionist">Nutritionist</option>
                            <option value="Cardiologist">Cardiologist</option>
                        <?php else: ?>
                            <option value="Please Select">Please Select</option>    
                            <option value="General">General</option>
                            <option value="Nutritionist">Nutritionist</option>
                            <option value="Cardiologist">Cardiologist</option>
                        <?php endif ?>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="from_time">From Time</label>
                <div class="col-sm-4">
                    <input type="time" id="from_time" name="from_time" 
                    <?php if($update === true): ?>
                        value = "<?php echo $result['from_time']?>"
                    <?php else: ?>
                        <?php echo ""?>
                    <?php endif ?> required>
                </div>
            </div>
            <div class="form-group row">
                <label for="to_time">To Time</label>
                <div class="col-sm-4">
                    <input type="time" id="to_time" name="to_time"
                    <?php if($update === true): ?>
                        value = "<?php echo $result['to_time']?>"
                    <?php else: ?>
                        <?php echo ""?>
                    <?php endif ?> required>
                </div>
            </div>
            <div class="form-group row">
                <?php if($update === true) { ?>
                    <label for="status">Status</label>
                    <div class="col-sm-4">
                        <input type="text" id="status" name="status" value="<?php echo $result['status'] ?>">
                    </div>
                <?php } ?>
            </div>
            <div class="form-group row">
                <div class="offset-sm-2 col-sm-10">
                    <?php if($update===true): ?>
                        <input type="submit" value="Update" name="submit">
                    <?php else: ?>
                        <input type="submit" id="Save" value="Save" name="submit">
                    <?php endif ?>
                </div>
            </div>
        </fieldset>
    </form>
</div>