<head>
    <link rel="stylesheet" href="views/css/ListDoctors.css">
</head>
<?php 
if ($_SESSION['role']==="staff") {
  require_once("views/StaffHome.phtml");
  $doctors = new DoctorData();
  $doctorsList = $doctors->listDoctors(); 
  $country = new CountryData();
  $state = new StateData();
  $record_per_page = 5;
  if(isset($_GET["page"])) {
      $page = $_GET["page"];
  } else {
      $page = 1;
  }
  $start_from = ($page-1) * $record_per_page;
  $doctorLimit = $doctors->listPerPage($start_from,$record_per_page);
?>
<div class="searchBox">
    <form action="ListDoctors" method="GET">
        <input type="text" id="search" name="search" placeholder="&#128269 Search">
        <input type="submit" name="submit" value="Search">
    </form>
</div>
<?php
if(isset($_GET['search'])) {
    $search = $_GET['search'];
    $doctorName = new DoctorData();
    $SearchDoctorName = $doctorName->SearchDoctorName($search);
    if($SearchDoctorName->rowCount() === 0) {
        $this->messageManager->addErrorMessage("Record Not Found");
        $this->redirect('ListDoctors');
    }
    if($SearchDoctorName->rowCount() > 0) { ?>
    <div>
        <table>
            <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Contact</th>
            <th>Email</th>
            <th>District</th>
            <th>State</th>
            <th>Country</th>
            <th>Actions</th>
        </thead>
        <tbody>
            <?php while ($row = $SearchDoctorName->fetch(PDO::FETCH_ASSOC)) {
                ?>
                <tr>
                    <td><?= $row['d_id']?></td>
                    <td><?= $row['firstname'] ?></td>
                    <td><?= $row['lastname'] ?></td>
                    <td><?= $row['gender'] ?></td>
                    <td><?= $row['contact'] ?></td>
                    <td><?= $row['email'] ?></td>
                    <td><?= $row['district'] ?></td>
                    <td><?php 
                    if(is_numeric($row['state'])){
                        $State = $state->SelectStateName($row['state']);
                        echo $State;
                    } else {
                        echo $row['state'];
                    }
                    ?></td>
                    <td><?php 
                    if(is_numeric($row['country'])){
                        $Country = $country->SelectCountryName($row['country']);
                        echo $Country;
                    } else {
                        echo $row['country'];
                    }
                    ?></td>
                    <td><button><a href="ViewDoctor?d_id=<?= $row['d_id']?>">View</a></button>  <button><a href="doctor?d_id=<?= $row['d_id']?>">Edit</a></button></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    </div>
<?php } 
} else { ?>
<div>
    <table>
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Contact</th>
            <th>Email</th>
            <th>District</th>
            <th>State</th>
            <th>Country</th>
            <th>Actions</th>
        </thead>
        <tbody>
            <?php while ($row = $doctorLimit->fetch(PDO::FETCH_ASSOC)) {
                ?>
                <tr>
                    <td><?= $row['d_id']?></td>
                    <td><?= $row['firstname'] ?></td>
                    <td><?= $row['lastname'] ?></td>
                    <td><?= $row['gender'] ?></td>
                    <td><?= $row['contact'] ?></td>
                    <td><?= $row['email'] ?></td>
                    <td><?= $row['district'] ?></td>
                    <td><?php 
                    if(is_numeric($row['state'])){
                        $State = $state->SelectStateName($row['state']);
                        echo $State;
                    } else {
                        echo $row['state'];
                    }
                    ?></td>
                    <td><?php 
                    if(is_numeric($row['country'])){
                        $Country = $country->SelectCountryName($row['country']);
                        echo $Country;
                    } else {
                        echo $row['country'];
                    }
                    ?></td>
                    <td><button><a href="ViewDoctor?d_id=<?= $row['d_id']?>">View</a></button>  <button><a href="doctor?d_id=<?= $row['d_id']?>">Edit</a></button></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<div class="pagination">
    <?php 
        $total_records = $doctors->countRecords();
        $total_pages = ceil($total_records/$record_per_page);
        $pageLink = "";
        for ($i=1; $i<=$total_pages; $i++) {   
            if ($i == $page) {   
                $pageLink .= "<a class='active' href='ListDoctors?page=".$i."'>".$i."</a>";   
            }               
            else  {   
                $pageLink .= "<a href='ListDoctors?page=".$i."'>".$i."</a>";     
            }   
        };
        echo $pageLink;       
    ?>
</div>
<?php } ?>
<?php } ?>
<?php 
if ($_SESSION['role']==="admin") {
  require_once("views/AdminHome.phtml");
  $doctors = new DoctorData();
  $doctorsList = $doctors->listDoctors(); 
  $country = new CountryData();
  $state = new StateData();
  $record_per_page = 5;
  if(isset($_GET["page"])) {
      $page = $_GET["page"];
  } else {
      $page = 1;
  }
  $start_from = ($page-1) * $record_per_page;
  $doctorLimit = $doctors->listPerPage($start_from,$record_per_page);
  //print_r($patientLimit);die;
?>
<div class="searchBox">
    <form action="ListDoctors" method="GET">
        <input type="text" id="search" name="search" placeholder="&#128269 Search">
        <input type="submit" name="submit" value="Search">
    </form>
</div>
<?php
if(isset($_GET['search'])) {
    $search = $_GET['search'];
    $doctorName = new DoctorData();
    $SearchDoctorName = $doctorName->SearchDoctorName($search);
    if($SearchDoctorName->rowCount() === 0) {
        $this->messageManager->addErrorMessage("Record Not Found");
        $this->redirect('ListDoctors');
    }
    if($SearchDoctorName->rowCount() > 0) { ?>
    <div>
        <table>
            <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Contact</th>
            <th>Email</th>
            <th>District</th>
            <th>State</th>
            <th>Country</th>
            <th>Actions</th>
        </thead>
        <tbody>
            <?php while ($row = $SearchDoctorName->fetch(PDO::FETCH_ASSOC)) {
                ?>
                <tr>
                    <td><?= $row['d_id']?></td>
                    <td><?= $row['firstname'] ?></td>
                    <td><?= $row['lastname'] ?></td>
                    <td><?= $row['gender'] ?></td>
                    <td><?= $row['contact'] ?></td>
                    <td><?= $row['email'] ?></td>
                    <td><?= $row['district'] ?></td>
                    <td><?php 
                    if(is_numeric($row['state'])){
                        $State = $state->SelectStateName($row['state']);
                        echo $State;
                    } else {
                        echo $row['state'];
                    }
                    ?></td>
                    <td><?php 
                    if(is_numeric($row['country'])){
                        $Country = $country->SelectCountryName($row['country']);
                        echo $Country;
                    } else {
                        echo $row['country'];
                    }
                    ?></td>
                    <td><button><a href="ViewDoctor?d_id=<?= $row['d_id']?>">View</a></button>  <button><a href="doctor?d_id=<?= $row['d_id']?>">Edit</a></button></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    </div>
<?php } 
} else { ?>
<div>
    <table>
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Contact</th>
            <th>Email</th>
            <th>District</th>
            <th>State</th>
            <th>Country</th>
            <th>Actions</th>
        </thead>
        <tbody>
            <?php while ($row = $doctorLimit->fetch(PDO::FETCH_ASSOC)) {
                ?>
                <tr>
                    <td><?= $row['d_id']?></td>
                    <td><?= $row['firstname'] ?></td>
                    <td><?= $row['lastname'] ?></td>
                    <td><?= $row['gender'] ?></td>
                    <td><?= $row['contact'] ?></td>
                    <td><?= $row['email'] ?></td>
                    <td><?= $row['district'] ?></td>
                    <td><?php 
                    if(is_numeric($row['state'])){
                        $State = $state->SelectStateName($row['state']);
                        echo $State;
                    } else {
                        echo $row['state'];
                    }
                    ?></td>
                    <td><?php 
                    if(is_numeric($row['country'])){
                        $Country = $country->SelectCountryName($row['country']);
                        echo $Country;
                    } else {
                        echo $row['country'];
                    }
                    ?></td>
                    <td><button><a href="ViewDoctor?d_id=<?= $row['d_id']?>">View</a></button>  <button><a href="doctor?d_id=<?= $row['d_id']?>">Edit</a></button></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<div class="pagination">
    <?php 
        $total_records = $doctors->countRecords();
        $total_pages = ceil($total_records/$record_per_page);
        $pageLink = "";
        for ($i=1; $i<=$total_pages; $i++) {   
            if ($i == $page) {   
                $pageLink .= "<a class='active' href='ListDoctors?page=".$i."'>".$i."</a>";   
            }               
            else  {   
                $pageLink .= "<a href='ListDoctors?page=".$i."'>".$i."</a>";     
            }   
        };
        echo $pageLink;       
    ?>
</div>
<?php } ?>
<?php } ?>

