<head>
    <link rel="stylesheet" href="views/css/profile1.css">
    <script type="text/javascript" src="views/js/showImage.js"></script>
</head>
<?php 
if ($_SESSION['role'] === 'admin') {
  require_once("views/AdminHome.phtml");
} 
if ($_SESSION['role'] === 'staff') {
  require_once("views/StaffHome.phtml");
} 
if ($_SESSION['role'] === "patient") {
  require_once("views/PatientHome.phtml");
} 
if ($_SESSION['role']==='doctor') {
  require_once("views/DoctorHome.phtml");
} 
if ($_SESSION['role'] === "admin") {
    $admin = new AdminData();
    $adminDetails = $admin->profile();
    $cookie = json_decode($_COOKIE['userdata'],true);
    $adminDetail = $adminDetails[0];
    $images = new ImageData();
    $admin_image = $images->selectImage($cookie['id']);
?>
<center><h1>Admin Profile</h1></center>
<table>
    <thead>
        <tr>
            <th>Profile Image</th>
            <td><?php 
                $images = new ImageData();
                $admin_image = $images->selectImage($cookie['id']);
                if($admin_image == "") {
                    echo "<img src=views/DefaultProfile/profile.png width='150' height='150'>";
                } else {
                    echo "<img src=views/AdminImageUploads/".$admin_image." width='150' height='150'>";
                }
                ?>
            </td>
        </tr> 
        <tr>
            <th>User Name</th>
            <td><?= $adminDetail['role']?></td>
        </tr>  
        <tr>
            <th>User Email</th>
            <td><?= $adminDetail['email']?></td><br>
        </tr>
        <tr>
            <th>Change Password</th>
            <td>
                <form name="Password" action="ChangePassword?user_id=<?= $cookie['id']?>" method="POST">
                    <input type="submit" name="submit" value="Change Password" id="updatePass">
                </form>
            </td>
        </tr>
        <tr>
            <th>Change Profile Photo</th>
            <td>
                <form name="image_upload" action="ProfilePost" method="POST" enctype="multipart/form-data" onsubmit="return fileUploads();">
                    <input type="file" name="admin_image" id="myfile">
                    <input type="submit" name="submit" value="Upload" id="upload">
                </form>
                <p id="status"></p>
                <script type="text/javascript" src="views/js/fileUploads.js"></script>
            </td>
        </tr> 
    </thead>
</table>
<?php } ?>
<?php 
if ($_SESSION['role'] === "staff") {
    $staff = new StaffData();
    $cookie = json_decode($_COOKIE['userdata'],true);
    $staffDetails = $staff->profile($cookie['id']);
    $staffDetail = $staffDetails[0];
?>
<center><h1>Staff Profile</h1></center>
<table>
    <thead> 
        <tr>
            <th>Profile Image</th>
            <td><?php 
                $images = new ImageData();
                $staff_image = $images->selectStaffImage($cookie['id']);
                if($staff_image == "") {
                    echo "<img src=views/DefaultProfile/profile.png width='150' height='150'>";
                } else {
                    echo "<img src=views/StaffImageUploads/".$staff_image." width='150' height='150'>";
                }
                ?>
            </td>
        </tr>
        <tr>
            <th>User Name</th>
            <td><?= $staffDetail['name']?></td>
        </tr>  
        <tr>
            <th>User Email</th>
            <td><?= $staffDetail['email']?></td> 
        </tr>
        <tr>
            <th>Role</th>
            <td><?= $_SESSION['role']?></td> 
        </tr> 
        <tr>
            <th>Change Password</th>
            <td>
                <form name="Password" action="ChangePassword?user_id=<?= $cookie['id']?>" method="POST">
                    <input type="submit" name="submit" value="Change Password" id="updatePass">
                </form>
            </td>
        </tr>
        <tr>
            <th>Change Profile Photo</th>
            <td>
                <form id="image_upload" action="StaffProfilePost" name="image_upload" method="POST" enctype="multipart/form-data" onsubmit="return staffFileUploads();">
                    <input type="file" name="staff_image" id="myfile">
                    <input type="submit" name="submit" value="Upload" id="upload">
                </form>
                <p id="status"></p>
                <script type="text/javascript" src="views/js/staffFileUploads.js"></script>
            </td>
        </tr>
    </thead>
</table>
<?php } ?>
<?php 
if ($_SESSION['role'] === "patient") {
    $patient = new PatientData();
    $cookie = json_decode($_COOKIE['userdata'],true);
    $patientDetails = $patient->profile($cookie['id']);
    $patientDetail = $patientDetails[0];
?>
<center><h1>Patient Profile</h1></center>
<table>
    <thead>
        <tr>
            <th>Profile Image</th>
            <td><?php 
                $images = new ImageData();
                $patient_image = $images->selectPatientImage($cookie['id']);
                if($patient_image == "") {
                    echo "<img src=views/DefaultProfile/profile.png width='150' height='150'>";
                } else {
                    echo "<img src=views/PatientImageUploads/".$patient_image." width='150' height='150'>";
                }
                ?>
            </td>
        </tr>
        <tr>
            <th>User Name</th>
            <td><?= $patientDetail['firstname']?></td>
        </tr>  
        <tr>
            <th>User Email</th>
            <td><?= $patientDetail['email']?></td> 
        </tr> 
        <tr>
            <th>Gender</th>
            <td><?= $patientDetail['gender']?></td><br>
        </tr>
        <tr>
            <th>Age</th>
            <td><?= $patientDetail['age']?></td>
        </tr>
        <tr>
            <th>DOB</th>
            <td><?= date("d-M-Y",strtotime($patientDetail['dob'])) ?></td><br>
        </tr>
        <tr>
            <th>Change Password</th>
            <td>
                <form name="Password" action="ChangePassword?user_id=<?= $cookie['id']?>" method="POST">
                    <input type="submit" name="submit" value="Change Password" id="updatePass">
                </form>
            </td>
        </tr>
        <tr>
            <th>Change Profile Photo</th>
            <td>
                <form name="image_upload" action="PatientProfilePost" method="POST" enctype="multipart/form-data" onsubmit="return patientFileUpload();">
                    <input type="file" name="patient_image" id="myfile">
                    <input type="submit" name="submit" value="Upload" id="upload">
                </form>
                <p id="status"></p>
                <script type="text/javascript" src="views/js/patientFileUpload.js"></script>
            </td>
        </tr>
    </thead>
</table>
<?php } ?>
<?php 
if ($_SESSION['role']==="doctor") {
    $doctor = new DoctorData();
    $cookie = json_decode($_COOKIE['userdata'],true);
    $doctorList = $doctor->profile($cookie['id']);
    $doctorDetail = $doctorList[0];
?>
<center><h1>Doctor Profile</h1></center>
<table>
    <thead>
        <tr>
            <th>Profile Image</th>
            <td><?php 
                $images = new ImageData();
                $doctor_image = $images->selectDoctorImage($cookie['id']);
                if($doctor_image == "") {
                    echo "<img src=views/DefaultProfile/profile.png width='150' height='150'>";
                } else {
                    echo "<img src=views/DoctorImageUploads/".$doctor_image." width='150' height='150'>";
                }
                ?>
            </td>
        </tr>
        <tr>
            <th>User Name</th>
            <td><?= $doctorDetail['firstname']?></td>
        </tr>  
        <tr>
            <th>Gender</th>
            <td><?= $doctorDetail['gender']?></td> 
        </tr> 
        <tr>
            <th>User Email</th>
            <td><?= $doctorDetail['email']?></td><br>
        </tr>
        <tr>
            <th>Age</th>
            <td><?= $doctorDetail['age']?></td>
        </tr>
        <tr>
            <th>DOB</th>
            <td><?= date("d-M-Y",strtotime($doctorDetail['dob'])) ?></td><br>
        </tr>
        <tr>
            <th>Qualification</th>
            <td><?= $doctorDetail['qualification']?></td>
        </tr>
        <tr>
            <th>Change Password</th>
            <td>
                <form name="Password" action="ChangePassword?user_id=<?= $cookie['id']?>" method="POST">
                    <input type="submit" name="submit" value="Change Password" id="updatePass">
                </form>
            </td>
        </tr>
        <tr>
            <th>Change Profile Photo</th>
            <td>
                <form id="image_upload" action="DoctorProfilePost" name="image_upload" method="POST" enctype="multipart/form-data" onsubmit="return doctorFileUpload();">
                    <input type="file" name="doctor_image" id="myfile">
                    <input type="submit" name="submit" value="Upload" id="upload">
                </form>
                <p id="status"></p>
                <script type="text/javascript" src="views/js/doctorFileUpload.js"></script>
            </td>
        </tr>
    </thead>
</table>
<?php } ?>
