<head>
    <link rel="stylesheet" href="views/css/ViewPage.css">
</head>
<?php 
if ($_SESSION['role'] === "admin") {
  require_once("views/AdminHome.phtml");
} 
if ($_SESSION['role']==="staff") {
  require_once("views/StaffHome.phtml");
} 
$doctors = new DoctorData();
$appointmentData = new AppointmentData();
if (isset($_GET['d_id'])) {
    $id = $_GET['d_id'];
    $row = $doctors->viewDoctor($id);
    $appointment = $appointmentData->listAppointment($id);
}
?>
<div>
    <table>
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Contact</th>
            <th>Age</th>
            <th>Address</th>
            <th>Qualification</th>
            <th>Email</th>
            <th>DOB</th>
            <th>District</th>
            <th>State</th>
            <th>Country</th>
            <th>Pincode</th>
        </thead>
        <tbody>
            <tr>
                <td><?= $row['d_id'] ?></td>
                <td><?= $row['firstname'] ?></td>
                <td><?= $row['lastname'] ?></td>
                <td><?= $row['gender'] ?></td>
                <td><?= $row['contact'] ?></td>
                <td><?= $row['age'] ?></td>
                <td><?= $row['address'] ?></td>
                <td><?= $row['qualification'] ?></td>
                <td><?= $row['email'] ?></td>
                <td><?= date("d-M-Y",strtotime($row['dob'])) ?></td>
                <td><?= $row['district'] ?></td>
                <td><?= $row['state'] ?></td>
                <td><?= $row['country'] ?></td>
                <td><?= $row['pincode'] ?></td>
            </tr>
        </tbody>
    </table>
</div>
<h1><center>Appointment Details</center></h1>
<div style="overflow-x:auto;">
    <table>
        <thead>
            <th>ID</th>
            <th>Patient Name</th>
            <th>Appointment Date</th>
            <th>From Time</th>
            <th>To Time</th>
            <th>Status</th>
        </thead>
        <tbody>
          <?php while ($row = $appointment->fetch(PDO::FETCH_ASSOC)) { ?>
          <tr>
            <td><?= $row['appointment_id']?></td>
            <td><?php
                $patient = new PatientData();
                $firstname = $patient->selectName($row['patient_id']);
                echo $firstname ?>
            </td>
            <td><?= $row['appointment_date']?></td>
            <td><?= $row['appointment_from_time']?></td>
            <td><?= $row['appointment_to_time']?></td>
            <td><?= $row['status']?></td>
          </tr>
          <?php } ?>
        </tbody>
    </table>
</div>