<h2>Login </h2>

<form name="login" method="POST" action="LoginPost">
    <p>
        <label for="email">Enter email id</label>
        <input type="text" id="email" name="email">
    </p>
    <p>
        <label for="password">Enter Password</label>
        <input type="password" id="password" name="password">
    </p>
    <p>
        <input type="submit" value="Login" name="Login">
    </p>
</form>