<h1>Register Form</h1>
<form name="register" method = "POST" id="register" action ="RegisterPost">
    </p>
        <label for="firstname">Enter First Name</label>
        <input type="text" id="firstname" name="firstname">
    </p>
    <p>
        <label for="lastname">Enter Last Name</label>
        <input type="text" id="lastname" name="lastname">
    </p>
    <p>
        <label for="email">Enter email address</label>
        <input type="email" id="email" name="email" > 
    </p>
    <p>
        <label for="password">Enter Password</label>
        <input type="password" id="password" name="password" maxlength = 10>
    </p>
    <p>
        <input type="submit" value="submit" name ="submit">
    </p>
</form>

