<h1>User Details</h1>
<section>
    <h2>Add Staff</h2>
    <div>
        <form name="staff" method="POST" action="staff">
            <input type="submit" value="staff" name="staff">
        </form>
    </div>
</section>
<section>
    <h2>Add Patient</h2>
    <div>
        <form name="patient" method="POST" action="patient">
            <input type="submit" value="patient" name="patient">
        </form>
    </div>
</section>
<section>
    <h2>Add Doctor</h2>
    <div>
        <form name="doctor" method="POST" action="doctor">
            <input type="submit" value="doctor" name="doctor">
        </form>
    </div>
</section>
