<head>
    <link rel="stylesheet" href="views/nav.css">
</head>
<div class="navbar">
  <a href="admin">Home</a>
  <div class="subnav">
    <button class="subnavbtn">Staff</button>
    <div class="subnav-content">
      <a href="staff">Add Staff</a>
      <a href="updateStaff">Update Staff</a>
    </div>
  </div>
  <div class="subnav">
    <button class="subnavbtn">Patient</button>
    <div class="subnav-content">
      <a href="patient">Add Patient</a>
      <a href="updatePatient">Update Patient</a>
    </div>
  </div>
  <div class="subnav">
    <button class="subnavbtn">Doctor</button>
    <div class="subnav-content">
      <a href="doctor">Add Doctor</a>
      <a href="updateDoctor">Update Doctor</a>
    </div>
  </div>