<h1>Doctor Details</h1>
<form name="doctorLogin" method="POST" action="DoctorPost">
    <p>
        <label for="firstname">Enter first name</label>
        <input type="text" id="firstname" name="firstname">
    </p>
    <p>
        <label for="lastname">Enter last name</label>
        <input type="text" id="lastname" name="lastname">
    </p>
    <p>
        <p>Select Gender</p>
        <input type="radio" id="male" name="gender" value="male">
        <label for="male">Male</label>
        <input type="radio" id="female" name="gender" value="female">
        <label for="female">Female</label>
    </p>
    <p>
        <label for="dob">Enter Date Of Birth</label>
        <input type="date" id="dob" name="dob">
    </p>
    <p>
        <label for="age">Enter age</label>
        <input type="number" id="age" name="age">
    </p>
    <p>
        <label for="email">Enter email id</label>
        <input type="email" id="email" name="email">
    </p>
    <p>
        <label for="contact">Enter Contact Number</label>
        <input type="tel" id="contact" name="contact" pattern="[0-9]{10}">
    </p>
    <p>
        <label for="password">Enter Password</label>
        <input type="password" id="password" name="password">
    </p>
    <p>
        <label for="address">Enter Address</label>
        <textarea name="address" id="address">Enter address here</textarea>
    </p>
    <p>
        <input type="submit" value="addDoctor" name="addDoctor">
    </p>
</form>