<?php 
if($_SESSION['role']==="admin"){
?>
<nav>
  <ul>
    <li><a href="AdminHome">Home</a></li>
    <li><a>Patient</a>
      <ul class="dropdown">
        <li><a href="Patient">Add Patient</a></li>
        <li><a href="ListPatients">List Patient</a></li>
      </ul>
    </li>
    <li><a>Staff</a>
      <ul class="dropdown">
        <li><a href="staff">Add Staff</a></li>
        <li><a href="ListStaffs">List Staff</a></li>
      </ul>
    </li>
    <li><a>Doctor</a>
      <ul class="dropdown">
        <li><a href="Doctor">Add Doctor</a></li>
        <li><a href="ListDoctors">List Doctor</a></li>
      </ul>
    </li>
    <li class="profile"><a href="profile">My Profile</a></li>
    <li class="logout"><a href="logout">Logout</a></li>
  </ul>
</nav>
<?php
$staff = new StaffData();
?>
<?php $staffList = $staff->listStaff(); ?>
<div><br>
    <table>
        <thead>
            <th>ID</th>
            <th>Staff Name</th>
            <th>Email</th>
            <th>Actions</th>
        </thead>
        <tbody>
            <?php while ($row = $staffList->fetch(PDO::FETCH_ASSOC)) {
                ?>
                <tr>
                    <td><?= $row['staff_id']?></td>
                    <td><?= $row['name'] ?></td>
                    <td><?= $row['email'] ?></td>
                    <td><button><a href="updateStaff?staff_id=<?= $row['staff_id']?>">Edit</a></button></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<?php } ?>