<?php 
if($_SESSION['role']==="doctor"){
?>
<nav>
  <ul>
    <li><a href="DoctorHome">Home</a></li>
    <li><a>Doctor</a>
      <ul class="dropdown">
        <li><a href="ListPatients">List Patients</a></li>
      </ul>
    </li>
    <li class="profile"><a href="profile">My Profile</a></li>
    <li class="logout"><a href="logout">Logout</a></li>
  </ul>
</nav>
<?php
$patients = new PatientData();
?>
<?php $patientsList = $patients->listPatients(); ?>
<div><br>
    <table>
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Contact</th>
            <th>Email</th>
            <th>District</th>
            <th>State</th>
            <th>Country</th>
            <th>Actions</th>
        </thead>
        <tbody>
            <?php while ($row = $patientsList->fetch(PDO::FETCH_ASSOC)) {
                ?>
                <tr>
                    <td><?= $row['p_id']?></td>
                    <td><?= $row['firstName'] ?></td>
                    <td><?= $row['lastName'] ?></td>
                    <td><?= $row['gender'] ?></td>
                    <td><?= $row['contact'] ?></td>
                    <td><?= $row['email'] ?></td>
                    <td><?= $row['district'] ?></td>
                    <td><?= $row['state'] ?></td>
                    <td><?= $row['country'] ?></td>
                    <td><button><a href="ViewPatient?p_id=<?= $row['p_id']?>">View</a></button>  <button><a href="addPresb?p_id=<?= $row['p_id']?>">Add Presb</a></button></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<?php } ?>
<?php 
if($_SESSION['role']==="staff"){
?>
<nav>
  <ul>
    <li><a href="StaffHome">Home</a></li>
    <li><a>Patient</a>
      <ul class="dropdown">
        <li><a href="Patient">Add Patient</a></li>
        <li><a href="ListPatients">List Patient</a></li>
      </ul>
    </li>
    <li><a>Doctor</a>
      <ul class="dropdown">
        <li><a href="Doctor">Add Doctor</a></li>
        <li><a href="ListDoctors">List Doctor</a></li>
      </ul>
    </li>
    <li class="profile"><a href="profile">My Profile</a></li>
    <li class="logout"><a href="logout">Logout</a></li>
  </ul>
</nav>
<?php
$patients = new PatientData();
?>
<?php $patientsList = $patients->listPatients(); ?>
<div><br>
    <table>
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Contact</th>
            <th>Email</th>
            <th>District</th>
            <th>State</th>
            <th>Country</th>
            <th>Actions</th>
        </thead>
        <tbody>
            <?php while ($row = $patientsList->fetch(PDO::FETCH_ASSOC)) {
                ?>
                <tr>
                    <td><?= $row['p_id']?></td>
                    <td><?= $row['firstName'] ?></td>
                    <td><?= $row['lastName'] ?></td>
                    <td><?= $row['gender'] ?></td>
                    <td><?= $row['contact'] ?></td>
                    <td><?= $row['email'] ?></td>
                    <td><?= $row['district'] ?></td>
                    <td><?= $row['state'] ?></td>
                    <td><?= $row['country'] ?></td>
                    <td><button><a href="ViewPatient?p_id=<?= $row['p_id']?>">View</a></button>  <button><a href="updatePatient?p_id=<?= $row['p_id']?>">Edit</a></button></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<?php } ?>
<?php 
if($_SESSION['role']==="patient"){
?>
<nav>
  <ul>
    <li><a href="PatientHome">Home</a></li>
    <li><a>Patient</a>
      <ul class="dropdown">
        <li><a href="ListPatients">List Patient</a></li>
      </ul>
    </li>
    <li class="profile"><a href="profile">My Profile</a></li>
    <li class="logout"><a href="logout">Logout</a></li>
  </ul>
</nav>
<?php
$patients = new PatientData();
?>
<?php 
$cookie=json_decode($_COOKIE['userdata'],true);
$patientsList = $patients->profile($cookie['id']); ?>
<div><br>
    <table>
        <thead>
          <th>ID</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Gender</th>
          <th>Contact</th>
          <th>Email</th>
          <th>District</th>
          <th>State</th>
          <th>Country</th>
          <th>Actions</th>
        </thead>
        <tbody>
          <tr>
            <td><?= $patientsList[0]['p_id']?></td>
            <td><?= $patientsList[0]['firstName'] ?></td>
            <td><?= $patientsList[0]['lastName'] ?></td>
            <td><?= $patientsList[0]['gender'] ?></td>
            <td><?= $patientsList[0]['contact'] ?></td>
            <td><?= $patientsList[0]['email'] ?></td>
            <td><?= $patientsList[0]['district'] ?></td>
            <td><?= $patientsList[0]['state'] ?></td>
            <td><?= $patientsList[0]['country'] ?></td>
            <td><button><a href="ViewPatient?p_id=<?= $patientsList[0]['p_id']?>">View</a></button></td>
          </tr>
        </tbody>
    </table>
</div>
<?php } ?>
<?php 
if($_SESSION['role']==="admin"){
?>
<nav>
  <ul>
    <li><a href="AdminHome">Home</a></li>
    <li><a>Patient</a>
      <ul class="dropdown">
        <li><a href="Patient">Add Patient</a></li>
        <li><a href="ListPatients">List Patient</a></li>
      </ul>
    </li>
    <li><a>Staff</a>
      <ul class="dropdown">
        <li><a href="staff">Add Staff</a></li>
        <li><a href="ListStaffs">List Staff</a></li>
      </ul>
    </li>
    <li><a>Doctor</a>
      <ul class="dropdown">
        <li><a href="Doctor">Add Doctor</a></li>
        <li><a href="ListDoctors">List Doctor</a></li>
      </ul>
    </li>
    <li class="profile"><a href="profile">My Profile</a></li>
    <li class="logout"><a href="logout">Logout</a></li>
  </ul>
</nav>
<?php
$patients = new PatientData();
?>
<?php $patientsList = $patients->listPatients(); ?>
<div><br>
    <table>
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Contact</th>
            <th>Email</th>
            <th>District</th>
            <th>State</th>
            <th>Country</th>
            <th>Actions</th>
        </thead>
        <tbody>
            <?php while ($row = $patientsList->fetch(PDO::FETCH_ASSOC)) {
                ?>
                <tr>
                    <td><?= $row['p_id']?></td>
                    <td><?= $row['firstName'] ?></td>
                    <td><?= $row['lastName'] ?></td>
                    <td><?= $row['gender'] ?></td>
                    <td><?= $row['contact'] ?></td>
                    <td><?= $row['email'] ?></td>
                    <td><?= $row['district'] ?></td>
                    <td><?= $row['state'] ?></td>
                    <td><?= $row['country'] ?></td>
                    <td><button><a href="ViewPatient?p_id=<?= $row['p_id']?>">View</a></button>  <button><a href="updatePatient?p_id=<?= $row['p_id']?>">Edit</a></button></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<?php } ?>