<head>
    <style>
        body{
            background: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)),url("../views/css/images/login.jpg");
            background-repeat:no-repeat;
            background-attachment: fixed;
            background-size: cover;
        }
        h2{
            color:black;
        }
        .login{
            background: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6),lavender);
        }
        label {
            color:white;
        }
        #email{  
            width: 300px;  
            height: 30px;  
            border: none;  
            border-radius: 3px;  
            padding-left: 8px;  
        }  
        #password{  
            width: 300px;  
            height: 30px;  
            border: none;  
            border-radius: 3px;  
            padding-left: 8px;  
        }  
    </style>
</head>
<h2>Login </h2>
<div class="login">
<fieldset>
<form name="login" method="POST" action="LoginPost">
    <p>
        <label for="email">Enter Email Id</label><br><br>
        <input type="text" id="email" name="email">
    </p>
    <p>
        <label for="password">Enter Password</label><br><br>
        <input type="password" id="password" name="password">
    </p>
    <p>
        <label for="role">Select role</label>
        <select name="role" id="role">
            <option value="admin">Admin</option>
            <option value="staff">Staff</option>
            <option value="patient">Patient</option>
            <option value="doctor">Doctor</option>
        </select>
    </p>
    <p>
        <input type="submit" value="Login" name="Login" id="log">
    </p>
</form>
</fieldset>
</div>