<h2>Login </h2>

<form name="login" method="POST" action="LoginPost">
    <p>
        <label for="email">Enter email id</label>
        <input type="text" id="email" name="email">
    </p>
    <p>
        <label for="password">Enter Password</label>
        <input type="password" id="password" name="password">
    </p>
    <p>
        <label for="role">Select role</label>
        <select name="role" id="role">
            <option value="admin">Admin</option>
            <option value="staff">Staff</option>
            <option value="patient">Patient</option>
            <option value="doctor">Doctor</option>
        </select>
    </p>
    <p>
        <input type="submit" value="Login" name="Login">
    </p>
</form>