<head>
    <link rel="stylesheet" href="views/css/doctorReport.css">
</head>
<?php
if ($_SESSION['role']==="admin") {
  require_once("views/AdminHome.phtml");
  $staffs = new StaffData();
  $staffsList = $staffs->listStaff(); 
?>
<div>
    <button onclick= "StaffExport()" class="report">Export</button><br>
</div>

<div>
    <table> 
        <thead>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
        </thead>
        <tbody>
            <?php while ($row = $staffsList->fetch(PDO::FETCH_ASSOC)) {
                ?>
                <tr>
                    <td><?= $row['staff_id']?></td>
                    <td><?= $row['name'] ?></td>
                    <td><?= $row['email'] ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<?php } ?>