<h1>Staff Details</h1>
<form name="staffLogin" method="POST" action="StaffPost">
    <p>
        <label for="StaffName">Enter name</label>
        <input type="text" id="StaffName" name="StaffName">
    </p>
    <p>
        <label for="email">Enter email</label>
        <input type="email" id="email" name="email">
    </p>
    <p>
        <label for="password">Enter Password</label>
        <input type="password" id="password" name="password">
    </p>
    <p>
        <input type="submit" value="update" name="submit">
    </p>
</form>