<?php 
if($_SESSION['role']==="admin"){
?>
<nav>
  <ul>
    <li><a href="AdminHome">Home</a></li>
    <li><a>Patient</a>
      <ul class="dropdown">
        <li><a href="Patient">Add Patient</a></li>
        <li><a href="ListPatients">List Patient</a></li>
      </ul>
    </li>
    <li><a>Staff</a>
      <ul class="dropdown">
        <li><a href="staff">Add Staff</a></li>
        <li><a href="ListStaffs">List Staff</a></li>
      </ul>
    </li>
    <li><a>Doctor</a>
      <ul class="dropdown">
        <li><a href="Doctor">Add Doctor</a></li>
        <li><a href="ListDoctors">List Doctor</a></li>
      </ul>
    </li>
    <li class="profile"><a href="profile">My Profile</a></li>
    <li class="logout"><a href="logout">Logout</a></li>
  </ul>
</nav>
<?php } ?>
<?php 
if($_SESSION['role']==="staff"){
?>
<nav>
  <ul>
    <li><a href="StaffHome">Home</a></li>
    <li><a>Patient</a>
      <ul class="dropdown">
        <li><a href="Patient">Add Patient</a></li>
        <li><a href="ListPatients">List Patient</a></li>
      </ul>
    </li>
    <li><a>Doctor</a>
      <ul class="dropdown">
        <li><a href="Doctor">Add Doctor</a></li>
        <li><a href="listDoctor">List Doctor</a></li>
      </ul>
    </li>
    <li class="profile"><a href="profile">My Profile</a></li>
    <li class="logout"><a href="logout">Logout</a></li>
  </ul>
</nav> 
<?php } ?>

<?php
$doctors = new DoctorData();
if(isset($_GET['d_id'])){
    $id = $_GET['d_id'];
    $row = $doctors->viewDoctor($id);
}
?>
<div>
    <table>
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Contact</th>
            <th>Age</th>
            <th>Address</th>
            <th>Qualification</th>
            <th>Email</th>
            <th>DOB</th>
            <th>District</th>
            <th>State</th>
            <th>Country</th>
            <th>Pincode</th>
        </thead>
        <tbody>
            <tr>
                <td><?= $row['d_id'] ?></td>
                <td><?= $row['firstName'] ?></td>
                <td><?= $row['lastName'] ?></td>
                <td><?= $row['gender'] ?></td>
                <td><?= $row['contact'] ?></td>
                <td><?= $row['age'] ?></td>
                <td><?= $row['address'] ?></td>
                <td><?= $row['qualification'] ?></td>
                <td><?= $row['email'] ?></td>
                <td><?= date("d-M-Y",strtotime($row['dob'])) ?></td>
                <td><?= $row['district'] ?></td>
                <td><?= $row['state'] ?></td>
                <td><?= $row['country'] ?></td>
                <td><?= $row['pincode'] ?></td>
            </tr>
        </tbody>
    </table>
</div>