<head>
    <link rel="stylesheet" href="views/css/ViewPage.css">
</head>
<?php 
if ($_SESSION['role'] === "admin") {
  require_once("views/AdminHome.phtml");
} 
if ($_SESSION['role'] === "doctor") {
  require_once("views/DoctorHome.phtml");
} 
if ($_SESSION['role'] === "staff") {
  require_once("views/StaffHome.phtml");
}  
if ($_SESSION['role'] === "patient") {
  require_once("views/PatientHome.phtml");
} 
$patients = new PatientData();
$country = new CountryData();
$state = new StateData();
if (isset($_GET['p_id'])) {
    $id = $_GET['p_id'];
    $row = $patients->viewPatient($id);
}
?>
<h1><center>Patient Details</center></h1>
<div>
    <table>
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Gender</th>
            <th>Contact</th>
            <th>Age</th>
            <th>Address</th>
            <th>Email</th>
            <th>DOB</th>
            <th>District</th>
            <th>State</th>
            <th>Country</th>
            <th>Pincode</th>
        </thead>
        <tbody>
            <tr>
                <td><?= $row['p_id'] ?></td>
                <td><?= $row['firstname'] ?></td>
                <td><?= $row['lastname'] ?></td>
                <td><?= $row['gender'] ?></td>
                <td><?= $row['contact'] ?></td>
                <td><?= $row['age'] ?></td>
                <td><?= $row['address'] ?></td>
                <td><?= $row['email'] ?></td>
                <td><?= date("d-M-Y",strtotime($row['dob'])) ?></td>
                <td><?= $row['district'] ?></td>
                <td><?php 
                    if(is_numeric($row['state'])){
                        $State = $state->SelectStateName($row['state']);
                        echo $State;
                    } else {
                        echo $row['state'];
                    }
                    ?></td>
                    <td><?php 
                    if(is_numeric($row['country'])){
                        $Country = $country->SelectCountryName($row['country']);
                        echo $Country;
                    } else {
                        echo $row['country'];
                    }
                    ?></td>
                <td><?= $row['pincode'] ?></td>
            </tr>
        </tbody>
    </table>
</div>
<?php 
if(isset($_GET['p_id'])){
  $id = $_GET['p_id'];
}
$presb = new Prescription();
$presbList = $presb->listPresb($id);

?>
<h1><center>Prescription Details</center></h1>
<div style="overflow-x:auto;">
    <table>
        <thead>
            <th>ID</th>
            <th>Doctor</th>
            <th>Disease</th>
            <th>Medicine</th>
            <th>Description</th>
            <th>Morning</th>
            <th>Noon</th>
            <th>Night</th>
        </thead>
        <tbody>
          <?php while ($row = $presbList->fetch(PDO::FETCH_ASSOC)) { ?>
          <tr>
              <td><?= $row['presb_id']?></td>
              <td><?= $row['firstname'] ?></td>
              <td><?= $row['disease'] ?></td>
              <td><?= $row['medicine'] ?></td>
              <td><?= $row['description'] ?></td>
              <td><?= $row['morning'] ?></td>
              <td><?= $row['noon'] ?></td>
              <td><?= $row['night'] ?></td>
          </tr>
          <?php } ?>
        </tbody>
    </table>
</div>
